### ISSUE TITLE
Incorrect reporting of function names

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#736]
## Description

Function names are reported incorrectly for the [Ethernaut token smart contract](https://ethernaut.zeppelin.solutions/level/0x6545df87f57d21cb096a0bfcc53a70464d062512).

## How to Reproduce

```
$ myth -x Desktop/ethernaut-token.sol 
==== Integer Underflow ====
SWC ID: 101
Type: Warning
Contract: Token
Function name: **ambiguous** many_msg_babbage(bytes1)
PC address: 469
Estimated Gas Usage: 758 - 1043
The subtraction can result in an integer underflow.

--------------------
In file: Desktop/ethernaut-token.sol:13

balances[msg.sender] - _value

--------------------

==== Integer Underflow ====
SWC ID: 101
Type: Warning
Contract: Token
Function name: **ambiguous** many_msg_babbage(bytes1)
PC address: 551
Estimated Gas Usage: 1291 - 1766
The subtraction can result in an integer underflow.

--------------------
In file: Desktop/ethernaut-token.sol:14

balances[msg.sender] -= _value

--------------------

==== Integer Overflow ====
SWC ID: 101
Type: Warning
Contract: Token
Function name: **ambiguous** many_msg_babbage(bytes1)
PC address: 627
Estimated Gas Usage: 6814 - 27479
This binary add operation can result in integer overflow.

--------------------
In file: Desktop/ethernaut-token.sol:15

balances[_to] += _value

--------------------
```

## Environment

- Mythril version: develop
- Solidity compiler and version: 0.4.24+commit.e67f0147.Darwin.appleclang
- Python version: 3.6.4
- OS and Version: Mac OS Mojave

**Comment by b-mueller** [comment]
I got this fixed by deleting `signatures.json`.

**Comment by cleanunicorn** [comment]
This does not reproduce for me

```shell
$ ./myth -x /tmp/token.sol
==== Integer Underflow ====
SWC ID: 101
Type: Warning
Contract: Token
Function name: transfer(address,uint256)
PC address: 469
Estimated Gas Usage: 758 - 1043
The subtraction can result in an integer underflow.

--------------------
In file: /tmp/token.sol:13

balances[msg.sender] - _value

--------------------

==== Integer Underflow ====
SWC ID: 101
Type: Warning
Contract: Token
Function name: transfer(address,uint256)
PC address: 551
Estimated Gas Usage: 1291 - 1766
The subtraction can result in an integer underflow.

--------------------
In file: /tmp/token.sol:14

balances[msg.sender] -= _value

--------------------

==== Integer Overflow ====
SWC ID: 101
Type: Warning
Contract: Token
Function name: transfer(address,uint256)
PC address: 627
Estimated Gas Usage: 6814 - 27479
This binary add operation can result in integer overflow.

--------------------
In file: /tmp/token.sol:15

balances[_to] += _value

--------------------
```

## Environment

- Mythril version: develop (b1c2139742d56ff302e60508c416033248f9ab1e)
- Solidity compiler and version: 0.4.24+commit.e67f0147.Linux.g++
- Python version: 3.6.7
- OS and Version: Arch Linux

Maybe this was fixed in the meantime

@b-mueller does this still happen for you on the develop branch?

**Comment by b-mueller** [comment]
@cleanunicorn I get a better result now with develop but the function names still contain `**ambiguos**`:

```
$ $MYTH -x token.sol 
==== Integer Underflow ====
SWC ID: 101
Type: Warning
Contract: Token
Function name: **ambiguous** transfer(address,uint256)
PC address: 469
Estimated Gas Usage: 758 - 1043
The subtraction can result in an integer underflow.

--------------------
In file: token.sol:13

balances[msg.sender] - _value

--------------------

==== Integer Underflow ====
SWC ID: 101
Type: Warning
Contract: Token
Function name: **ambiguous** transfer(address,uint256)
PC address: 551
Estimated Gas Usage: 1291 - 1766
The subtraction can result in an integer underflow.

--------------------
In file: token.sol:14

balances[msg.sender] -= _value

--------------------

==== Integer Overflow ====
SWC ID: 101
Type: Warning
Contract: Token
Function name: **ambiguous** transfer(address,uint256)
PC address: 627
Estimated Gas Usage: 6814 - 27479
This binary add operation can result in integer overflow.

--------------------
In file: token.sol:15

balances[_to] += _value

--------------------
```

Using the default signatures.json from the repo.

I'm not sure that the ambiguous function name detection is useful... it's worth logging this to logging.debug but the reported function name should definitely not be changed.

**Comment by JoranHonig** [comment]
If we are analyzing source code then maybe the signatures json should be ignored altogether, it can only result in negative consequences here.

**Comment by cleanunicorn** [comment]
Could #758 have an effect on how this behaves?

**Comment by dmuhs** [comment]
@cleanunicorn It could have, but doesn't. I can still reproduce the issue. The core gist here is that we take the source, compile it and then deduct the function names from the byte code again, which results in ambiguities - especially now that we have a larger signature DB.
